// import state from react
import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Alert from '@mui/material/Alert';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';

// Let's import our new form
import MovieFilterForm from '../components/MovieFilterForm'
// let's import the movielist component and see if it works
import MovieList from '../components/MovieList';

import { MOVIE_LIST } from '../utils/movies'

export default function Home() {
  // I also want you create stateful variables for the MOVIE_LIST (where the movie list)
  // will be the default value.
  const [movies, setMovies] = useState(MOVIE_LIST)

  return (
    <div>
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container>
          <Typography variant="h2" component="h2" style={{textAlign: "center"}}>
            Movies
          </Typography>
          {/* we want to make smaller reusable components
            we're going to create two components and we're
            going to pass state down.
            - one for MovieFilterForm
            - one for MovieList
            pass the state down use these in the code!
            import them and use them.

            Note: here this is going to be useful
            for assignment 3 as
          */}
          <MovieFilterForm
            movies={movies}
            setMovies={setMovies}
          />
          <MovieList
            movies={movies}
          />
        </Container>
      </main>
    </div>
  )
}
