import { useState, useEffect } from 'react'

import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import AgencyCard from '@components/AgencyCard';
import NavBar from '@components/NavBar';

import { getAgencies } from '@utils/api/agencies';

export default function Home() {
  // import the useState, useEffect
  // create a stateful value of agencies
  const [agencies, setAgencies] = useState([])
  const [loading, setLoading] = useState(true)
  // fetch that data
  const renderAgencies = async () => {
    setLoading(true)
    const data = await getAgencies()
    setLoading(false)
    console.log(data)
  }
  // when the page is loaded we're fetching the agencies
  useEffect(()=> {
    renderAgencies()
  }, [])

  // loop through and create those agencies.

  // handle the loading state "loading..."
  if (loading) {
    return <>Loading...</>
  }


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            Space Agencies
          </Typography>
          <Box
            sx={{
              marginTop: 2,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
          </Box>
        </Container>

    </div>
  )
}
